### ISSUE TITLE
invalid reads in check_is_wall

### ISSUE THREAD

**Issue by Han2-Ro** [Daniyel03/cub3d#21]
==244562== Invalid read of size 4
==244562==    at 0x402EA7: check_is_wall (render.c:38)
==244562==    by 0x40307E: next_wall_x (render.c:57)
==244562==    by 0x4033C1: next_wall (render.c:92)
==244562==    by 0x403700: draw_view (render.c:131)
==244562==    by 0x40190E: on_loop (hooks.c:44)
==244562==    by 0x487A354: mlx_loop (in /usr/lib/libmlx.so)
==244562==    by 0x4020AC: cub3d (main.c:69)
==244562==    by 0x4020F8: main (main.c:77)
==244562==  Address 0x4da4d68 is 20 bytes after a block of size 84 alloc'd
==244562==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==244562==    by 0x4024B1: validate_input (parser.c:69)
==244562==    by 0x4027D1: alloc_array (parser.c:136)
==244562==    by 0x401DF5: get_map (main.c:23)
==244562==    by 0x40204A: cub3d (main.c:63)
==244562==    by 0x4020F8: main (main.c:77)
==244562==

**Comment by Daniyel03** [comment]
alpha
