### ISSUE TITLE
walking and rendering

### ISSUE THREAD

**Issue by Daniyel03** [Daniyel03/cub3d#27]
invalid wall rendering:
![image](https://github.com/user-attachments/assets/873f7356-071e-4c4a-98e9-5e4bb66c0f69)

might has to do something with the fact that walking through a wall diagonally is possible (my part to fix);

meaning we could "glitch" thourgh the bottom right wall:

11111111
10N10011
10100111
11111111

but with the map given in the screenshot, walking through the border of and causing a seg fault still doesnt work since we got a whole -1 border around the walls.

**Comment by Daniyel03** [comment]
|| wall_pos.x < 1 would fix it:

![image](https://github.com/user-attachments/assets/472fc249-fc76-4955-961e-333dc2bf2fd1)

pls approve @Han2-Ro

**Comment by Han2-Ro** [comment]
I just removed this if statement with the power of structures.
